# This is a basic workflow to help you get started with Actions

name: My_action_home_work

# Controls when the action will run.  
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message
        run : echo "Hello World from testing job"


  my_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Message
        run : echo "Hello World from Deploy job"
