name: on_Linux_hw
env:
  APPLICATION_NAME : "myHome_Work"
  DEPLOY_PACKAGE_NAME     : "work-deploy-ver-${{ github.sha }}"
  
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on : ubuntu-latest
    
    steps:
      #- name: Git clone our repo
      # uses: actions/checkout@v1
        
      - name: ECH  
        run: echo "Hello"
      # Check OS
      - name: CheckOS
        run: uname -a
      # Check GCC version  
      - name: CheckGCC
        run: gcc --version 
      # Check G++ version  
      - name: CheckG++
        run: g++ --version
      # Check cmake version  
      - name: CheckCMake
        run: cmake --version
            
