name: on_Linux_hw
env:
  APPLICATION_NAME : "myHome_Work"
  DEPLOY_PACKAGE_NAME     : "work-deploy-ver-${{ github.sha }}"
  
on:
  push:
    branches:
      - master 

jobs:
  testing:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++" }
    
    steps:
        
      - name: CheckOS
        run : uname -a

      - name: CheckGCC
        run : gcc --version 
       
      - name: CheckG++
        run : g++ --version
        
      - name: CheckCMake
        run : cmake --version
        
      - name: Setup Ninja
        run: ninja --version
        #run : sudo apt-get install ninja-build
        
      - name: IF 
        if: failure()
        run: sudo apt-get install ninja-build
        
        
  build:
    runs-on : ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++" }
    #runs-on: ubuntu-latest
    needs   : [testing]
    
    steps:
    
      - name: Git clone our repo
        uses: actions/checkout@v1
        
      - name: Setup Ninja
        run : sudo apt-get install ninja-build
        
      - name: build_act
        run: |
          mkdir build
          cd build   
          # cmake -DCMAKE_C_COMPILER=gcc 9 -DCMAKE_CXX_COMPILER=g++ 9 ..
          cmake -G Ninja ..
          cmake --build .
          #make
          # Make tests
          ctest 
          # Install
          cmake --install .
